version: '3'

services:
  bat_web:
    image: webdevops/php-apache-dev:7.4
    container_name: bat_web
    user: root
    restart: always
    volumes:
      - "./:/app"
    environment:
      - WEB_ALIAS_DOMAIN=bat.loc
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_HOST=192.168.1.23
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_CLIENT_HOST=192.168.1.23
      - php.xdebug.remote_enable=1
      - php.xdebug.idekey=PHPSTORM
    ports:
      - "80:80"
      - "443:443"
      - "32834:22"
    links:
      - bat_db:mysql
  bat_db:
    image: mariadb:10
    container_name: bat_db
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bat
    ports:
      - "33067:3306"
